name: pub_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_svg: ^1.1.4
  freezed_annotation: ^2.1.0
  fstate: ^0.8.0+1
  html: ^0.15.0
  json_annotation: ^4.6.0
  pubspec_parse: ^1.2.1
  rxdart: ^0.27.7
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  fstate_generator: ^0.7.0
  json_serializable: ^6.3.0
  mockito: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/search_background.png
