name: fstate

repository: https://github.com/wurikiji/fstate.git

packages:
  - packages/*
  - packages/fstate/example/*

command:
  bootstrap:
    usePubspecOverrides: true

ide:
  intellij:
    enabled: false
