targets:
  $default:
    builders:
      fstate_generator:state_generator:
        enabled: true
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - unused_local_variable

builders:
  state_generator:
    import: "package:fstate_generator/builders.dart"
    builder_factories:
      - "stateGenerator"
    build_extensions: { ".dart": [".fstate.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [source_gen:combining_builder]
