name: fstate_generator
description: A dart code generator for fstate. See fstate for details.
version: 0.1.1+1
homepage: https://github.com/wurikiji/fstate
repository: https://github.com/wurikiji/fstate

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  analyzer: ^5.6.0
  build: ^2.3.1
  code_builder: ^4.4.0
  source_gen: ^1.2.7
  build_config: ^1.1.1
  path: ^1.8.2
  recase: ^4.1.0
  dart_style: ^2.3.0
  meta: ^1.8.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  fstate: ^0.1.1+1
  build_runner: ^2.3.3
  build_test: ^2.1.6
  lints: ^2.0.0
  test:
  rxdart: ^0.27.7
