name: fstate
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/wurikiji/fstate
repository: https://github.com/wurikiji/fstate

environment:
  sdk: ">=2.19.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  test_api: ^0.4.18
  test_core: ^0.4.24
